const experience=[
['Nokia','IP R&D Lab Technologist Co-op','Jan 2026 — Apr 2026','Ottawa, Canada','Enhanced an internal orders and inventory system with Vue.js, API integrations and MariaDB, while supporting Linux-based lab infrastructure and equipment operations.',['Vue.js & JavaScript','API integration','Linux lab support']],
['Pinefield','Full Stack Developer Co-op','Sep 2025 — Jan 2026','Ottawa / Remote','Built and tested a Python service around currency and Bitcoin data, deployed it to a Tencent Cloud serverless environment and investigated cloud configuration and Redis connectivity.',['Python','Docker','REST APIs','Cloud troubleshooting']],
['Policlínica de Barbalha','IT Support Analyst','Jan 2014 — Jun 2024','Ceará, Brazil','Owned day-to-day technology support for the healthcare unit, spanning users, Active Directory, VMware, endpoints, printers, networking, Wi-Fi and technology-connected medical equipment.',['Troubleshooting','Active Directory','VMware','Networks']],
['Televisão Verdes Mares','IT Support Analyst','Jul 2008 — Jan 2014','Ceará, Brazil','Provided hands-on support for systems, hardware, printers, network connectivity and end users in a production media environment.',['End-user support','Hardware','Networking']]];
const projects=[
['StudyHub Academic Planner','Term 4','CST8259 — Web Programming Languages II','Project','Summer 2026','A team-built academic planner with authenticated APIs for courses, assignments and study notes.','Backend setup, migrations, Eloquent relationships, Sanctum authentication, ownership validation, feature tests and API documentation.',['Laravel','PHP','SQLite','Sanctum','REST APIs'],'https://github.com/fernandomacedob/studyhub-academic-planner','The React frontend was led by another team member.'],
['Secure Student Notes Manager','Term 4','CST8265 — Web Security Basics','Project','Summer 2026','A side-by-side comparison of intentionally vulnerable and secured note-management applications.','Implemented and documented authentication, access control, safer database operations, security headers, rate limiting, audit logs and encrypted notes.',['Node.js','Express','MySQL','Security','AES-256-GCM'],'https://github.com/fernandomacedob/secure-student-notes-manager'],
['React Trivia SPA','Term 4','CST8259 — Web Programming Languages II','Lab','Summer 2026','A responsive trivia application consuming the Open Trivia Database API with persistent score history.','Built the component flow, question shuffling, API integration, browser persistence and automated tests as guided academic work.',['React','Vite','JavaScript','REST API','localStorage'],'https://github.com/fernandomacedob/lab7-trivia'],
['Grade Book API','Term 4','CST8259 — Web Programming Languages II','Lab','Summer 2026','A controller-based API for related students, assignments and grades with SQLite persistence.','Implemented CRUD endpoints and Entity Framework relationships while developing practical familiarity with the ASP.NET Core request flow.',['C#','ASP.NET Core','Entity Framework','SQLite'],'https://github.com/fernandomacedob/lab5-grade-book'],
['ITSG-33 Security Assessment Tracker','Term 4','CST8268 — Web Project','Project','Summer 2026','A team application for tracking security controls, assessment evidence and project workflow.','Contributed AI-assisted controller/API integration, interface alignment, testing and documentation within the team workflow.',['Laravel','Livewire','Blade','Tailwind','Git'],null,'Presented as AI-assisted project experience, not independent framework mastery.'],
['Task Manager','Term 3','Web Applications Development','Project','Summer 2025','A full-stack task-management application with authentication, priorities, due dates and responsive CRUD workflows.','Developed the application as a capstone-style academic project using Laravel and Livewire.',['Laravel','Livewire','PHP','MySQL','Bootstrap']],
['Invoice Manager','Term 3','Web Programming Languages I','Assignment','Summer 2025','A PHP application for creating, editing and deleting invoices with validation and session-based persistence.','Practised request handling, server-side validation, sessions and data-management fundamentals.',['PHP','HTML','CSS','JavaScript','Sessions']],
['Interactive Web UI Prototype','Term 2','Graphics Technologies','Project','Spring 2025','A complete interface concept developed from low-fidelity wireframes into an interactive visual prototype.','Created wireframes, visual assets, typography and color decisions, reusable UI components and the final presentation.',['Figma','Photoshop','Illustrator','UI/UX']],
['Bean Counters','Term 1','CST8209 — Web Programming I','Assignment','Fall 2024','An early interactive web assignment focused on browser events and real-time interface updates.','Built accessible increment, decrement and reset controls while practising DOM manipulation and input validation.',['HTML','CSS','JavaScript','DOM','Events'],'https://github.com/fernandomacedob/bean-counters']];
const byId=id=>document.getElementById(id);const esc=v=>{const n=document.createElement('span');n.textContent=v;return n.innerHTML};
function renderExperience(){byId('experience-list').innerHTML=experience.map((x,i)=>`<article class="timeline-item"><div class="timeline-marker"><span>${String(i+1).padStart(2,'0')}</span></div><div class="timeline-period"><strong>${x[2]}</strong><span>${x[3]}</span></div><div class="timeline-content"><p>${x[0]}</p><h3>${x[1]}</h3><p>${x[4]}</p><div class="tags">${x[5].map(t=>`<span>${t}</span>`).join('')}</div></div></article>`).join('')}
const term=byId('term-filter'),course=byId('course-filter'),type=byId('type-filter'),query=byId('project-search');
function options(select,values,label){select.innerHTML=`<option value="All">${label}</option>`+values.map(v=>`<option>${esc(v)}</option>`).join('')}
function populate(){const selected=term.value||'All';options(term,[...new Set(projects.map(p=>p[1]))].sort(),'All terms');term.value=selected;const terms=term.value==='All'?projects:projects.filter(p=>p[1]===term.value);const selectedCourse=course.value||'All';options(course,[...new Set(terms.map(p=>p[2]))].sort(),'All courses');course.value=[...course.options].some(o=>o.value===selectedCourse)?selectedCourse:'All'}
function render(){const q=query.value.trim().toLowerCase();const found=projects.filter(p=>(term.value==='All'||p[1]===term.value)&&(course.value==='All'||p[2]===course.value)&&(type.value==='All'||p[3]===type.value)&&(!q||[p[0],p[2],p[5],...p[7]].join(' ').toLowerCase().includes(q)));byId('result-count').textContent=found.length;byId('clear-filters').hidden=term.value==='All'&&course.value==='All'&&type.value==='All'&&!query.value;byId('project-grid').innerHTML=found.map(p=>`<article class="project-card"><div class="project-meta"><b>${p[1]}</b><span>${p[3]}</span><span>${p[4]}</span></div><h3>${p[0]}</h3><p class="course">${p[2]}</p><p class="project-summary">${p[5]}</p><div class="contribution"><span>My contribution</span><p>${p[6]}</p></div>${p[9]?`<p class="project-note">${p[9]}</p>`:''}<div class="project-tags">${p[7].map(t=>`<span>${t}</span>`).join('')}</div>${p[8]?`<a class="project-link" href="${p[8]}" target="_blank" rel="noopener noreferrer">View repository ↗</a>`:''}</article>`).join('');byId('empty-state').hidden=!!found.length}
function reset(){term.value='All';populate();course.value='All';type.value='All';query.value='';render()}
term.addEventListener('change',()=>{course.value='All';populate();render()});[course,type,query].forEach(e=>e.addEventListener(e===query?'input':'change',render));byId('clear-filters').addEventListener('click',reset);byId('reset-empty').addEventListener('click',reset);renderExperience();populate();render();
